sudo: false
language: node_js
node_js:
- '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Building Code
      script: travis_wait npm run build-storybook
    - stage: GitHub Release
      script: travis_wait npm run deploy
      deploy:
        provider: releases
        api_key: $GH_TOKEN
        skip_cleanup: true
        on:
          tags: true
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"