sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Deploy Code     
      before_script: 
        - npm run build-storybook
     deploy:
      provider: pages
      local-dir: public
      target-branch: gh-pages
      repo: front10/landing-page-book
      skip-cleanup: true
      github-token: $GH_TOKEN
      keep-history: true
      on:
       branch: master
env:
  global:
    - GH_USER: front10
    - GITHUB_REPO: landing-page-book
    - secure: "yRC/1a/wuzEn5mNQbskKuaagoYxmiasFBjy2bxw05iXnfBH2AN1ZHz9Gq9Mekw0/BePiIdQqcJTFvEDd/EC8YEkI7y54HCUe4vtV5vbL4Uur+G4q5vv7PbHQnsnARHTqqzIn7bG7zl0Zb/u/MuEae/DpQEEKbKLx/8CIA7bPl2L0mLccss57WtZhbfCgVzZSHO/D3bZPFAmqk058qT75CFpt22FY+IgIuWFNcUnBMg9RfgdgUTv4T8syB4G4AL6Ij3qm4wKYL+Fy9kcA3o6Y6Wlmp+UNs+yZjIML5AM0+KJ4JitQilnBJbu2+4CTWMUYa0H1RjAHyoSPfkD8/WvN3bsrGaWOrZTeKWEua6NI1JwQ8ebEmctqz6tkHRBB260NcQEVjiacbjRq55Wro4/sG6wiHkXx56Ilvu7Q7pv1fiNRpfyzp8IKeEh1PRkidqMuO+zvELQaC8uFXLWy0ZNm/dJrg075n3MQh/nKSKctlRCts1sfLxs9YnYqnno23E7Q/UZnvLY87w3DJU+xcB+ERTlzbAMkyqtwOnkomsN0d15luHR8VdkLI08InY1JOOAqWeJ2Xm8MV915dAyb5QN49nARRoSZLD+A+bi4rPVnyVLZUoHWLNJNYCNhHMKH26clFK4UCGNs4mOKk0nCxq9szqYb2nSvSLSvRsXkj6Fptmw="
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"