sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Test code
      script: npm run eslint 
      script: npm run test -- -u  
    - stage: Building code
      script: npm run build-storybook      
  deploy:
    provider: pages
    skip-cleanup: true
    github-token: secure: "C3skgHTCkqiBATIQVIHaFLBJiDk3VLmB+pMaDHYt35/nhtlztRGfvLx0d3uJ3IBNxk7EHXaXzyHs+CSFxfjPvIbe61YLcQPniu9V1V70c8WMSRRVtEePnppSVZrMY5fLfjyCRk/+tSj8OEY6NsAL6z2pS9w4Zvh3DqxKbH64TWabqZWJHe9o8qfThKPTrdjMaaBOpCveo8VzjlL00+qZ2yXCupWmgaS1XRyiqR9O507/rSB4/VnbyugkOum/HkIb5AkKCmdc8Mued6LHdfqE+0N5GnDAAfG5xWHVJrzmsjMwXg5hPQ1uiF07Wgy/w85QHVfsBWOVJ+RSC9tsEDsyZzfN/35GwmsbBPqgnDnjV6gkVnu/R/33HWLZyWhdzFA7RVgTuP0NuzurhOe/xC03m/FM2gnwoTHDM1jgyMycT7ZxJdIIgbQaw2IOECsZPKAuSuOsxo+991lA3d/ommyoai+4FVG1I82OpbHGrRUCeJDfTkJbpC9/xTrq6qQj30ACf14UlHS2Jd819vYlwRYN7bi7GLmrucdkDd+BH/VTrVSkAyuz/0mDG061rZwoHbqigA9K/r9IURufviV7AzbRLithu0FVc8F+ybO4hJ9H40i4+xYSnMsRauM/Lrqgmvp1NJaKUTFbnjtiS74ryImGlGwcYxgG4z/Qqv6NltJgkvw="
    keep-history: true
    local-dir: ./public
    repo: front10/landing-page-book
    target-branch: gh-pages
    on:
     branch: master
env:
  global:
  - GH_USER: front10
  - GH_REPO: landing-page-book
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"