sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Deploy Code     
      before_script: 
        - npm run build-storybook
        - git config --global user.email "systems@front10.com" && git config --global user.name "front10-circleci"
      script:
      - npm run deploy
env:
  global:
  - GH_USER: "front10"
  - GITHUB_REPO: "landing-page-book"
  - secure: "AX8VrjBzwVULLFqUTdjcnvM3FB9bp+vlNSDtgWg08jPbiojF3j+A2kND+d3OMOE10r4QfbQSPj/n7GspNIQZ62FiSVS4SeSZ1kar2rzblECimJ6zHxnoLPPGDdjzNTSSOL0Vk1VxutGbtHOM1GdceZgXNSI+1zekujhzlG49qGGjnEesjC4nv4quVNjmVEzB4DLcVKehNJi1YiUHpnpZTcqJI1XvUC2NscnKgkjPDmAoc6Tfm4a0Mf8lfwOxa2Zfms9Oemu9eEuihWFuabvPUxugHF/NDvNEzmX3eZo4xC06dG6yZLTuLOttda4fAo+Z06klVVTtNnwAmpxCIqDcENddDTT1EHQg1FuX3E5isqQkXbShgdAmwE4+O4b8WWS+/kfm1+fFqDDTnN/1stsoBJxqRYYmEVdKiCqRPHCC5p3nV9xMB86UGg5yj9BmpYcNWBBsDDn3iJyNwegDDvCbhOfOXWJFKPgpnhuclnmvhUCfXkDbZbDGHHnXRmnNI9m19gBHVBdE3PixMIOOjaS2V4t3NLAiMCi7SW3Pne3KkheCoGdrRzMcNnofg0gJdxbWEdGLsPQnUkFXlYxZIu9QiQzxUPmKqCLCiuWeB9vULKWmzZiEfv5at+XskaR8fmlZkp6Kts4BZ2fiiehTahvoqta2oqq+c74zZNQxzdyWSGk="
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"