sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Test code
      script: npm run eslint 
      script: npm run test -- -u  
    - stage: Building code
      script: npm run build-storybook      
  deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: ./public
    repo: git@github.com:front10/landing-page-book.git
    target-branch: gh-pages
    on:
     branch: master
env:
  global:
  - GH_USER: front10
  - GH_REPO: landing-page-book
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"