sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Test code
      script: npm run test
  deploy:
     provider: pages
     skip-cleanup: true
     github-token: $GH_TOKEN #try new
     keep-history: true
     local-dir: public
     repo: git@github.com:front10/landing-page-book.git
    on:
     branch: master
env:
  global:
  - GH_USER: front10
  - GH_REPO: landing-page-book
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"