sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Deploy Code     
      before_script: 
        - npm run build-storybook
        - git config --global user.email "ycbarrosocu@gmail.com" && git config --global user.name "rootlinux2"
      script:
      - npm run deploy
env:
  global:
    - GH_TOKEN: "dfdb5abe265beb6832cb1b8457b4bbef46d4b8b9"
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"