sudo: false
language: node_js
node_js:
 - '8.12'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: true
jobs:
  include:
    - stage: Installing dependencies
      script: npm install    
    - stage: Deploy Code
      if: branch = master
      before_script: npm run build-storybook
      script: npm run deploy   
env:
  global:
  - GH_TOKEN: "8394b3149797c253bb3f36c3673ef6f6557c08fe"
  - GH_USER: front10
  - GH_REPO: landing-page-book
addons:
  browserstack:
    username: "yoandrycollazo1"
    access_key: "keqUpLHUTfApAq2fM77i"