defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
    build:
        <<: *defaults
        steps:
         - checkout
         - attach_workspace:
             at: .
         - deploy:
             name: Deploy to GitHub Pages
             command:
                - "./scripts/deploy-ghpages.sh build"