version: 2 
jobs:
  build: 
    working_directory: ~/landing-page-book 
    docker: # 
      - image: circleci/node:8.12.0 
    branches:
      ignore:
       - gh-pages
    steps:
      - add_ssh_keys:
         fingerprints:
           - "31:f0:b9:be:9d:e5:e0:cc:51:71:8a:dc:69:1a:2a:3d"       
      - checkout        
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}      
      - run:
         name: Deploy to GitHub Pages
         command: './scripts/deploy-ghpages.sh'    
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules     
      - store_artifacts:
          path: public